###################################################################################################
## This constraints file contains default clock frequencies to be used during creation of a 
## Synthesis Design Checkpoint (DCP). For best results the frequencies should be modified 
## to match the target frequencies. 
## This constraints file is not used in top-down/global synthesis (not the default flow of Vivado).
###################################################################################################


##################################################################################################
## 
##  Xilinx, Inc. 2010            www.xilinx.com 
##  Mon Feb  6 13:16:24 2023

##  Generated by MIG Version 4.2
##  
##################################################################################################
##  File name :       DDR3LController.xdc
##  Details :     Constraints file
##                    FPGA Family:       SPARTAN7
##                    FPGA Part:         XC7S50-FGGA484
##                    Speedgrade:        -2
##                    Design Entry:      VHDL
##                    Frequency:         320.10000000000002 MHz
##                    Time Period:       3124 ps
##################################################################################################

##################################################################################################
## Controller 0
## Memory Device: DDR3_SDRAM->Components->MT41K256M16XX-107
## Data Width: 16
## Time Period: 3124
## Data Mask: 1
##################################################################################################