##################################################################################################
## 
##  Xilinx, Inc. 2010            www.xilinx.com 
##  Tue Nov  1 14:20:46 2022

##  Generated by MIG Version 4.2
##  
##################################################################################################
##  File name :       example_top.sd
##  Details :     Constraints file
##                    FPGA Family:       SPARTAN7
##                    FPGA Part:         XC7S75FGGA484_PKG
##                    Speedgrade:        -2
##                    Design Entry:      VHDL
##                    Frequency:         320.10000000000002 MHz
##                    Time Period:       3124 ps
##################################################################################################

##################################################################################################
## Controller 0
## Memory Device: DDR3_SDRAM->Components->MT41K256M16XX-107
## Data Width: 16
## Time Period: 3124
## Data Mask: 1
##################################################################################################

set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_ck_n[*]} ]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_ck_p[*]} ]
          
create_clock -period 6.248 [get_ports sys_clk_p]
          
create_clock -period 5 [get_ports clk_ref_p]
          
############## NET - IOSTANDARD ##################


