@echo off
REM ****************************************************************************
REM Vivado (TM) v2022.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Mar 14 11:16:58 -0500 2023
REM SW Build 3671981 on Fri Oct 14 05:00:03 MDT 2022
REM
REM IP Build 3669848 on Fri Oct 14 08:30:02 MDT 2022
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim Trigger_testbench_behav -key {Behavioral:sim_1:Functional:Trigger_testbench} -tclbatch Trigger_testbench.tcl -view C:/Users/mrigatti/Desktop/CRV/2.Firmware/FEB/DDR_Interface_testbench_behav.wcfg -view C:/Users/mrigatti/Desktop/CRV/2.Firmware/FEB/Trigger_testbench_behav2.wcfg -log simulate.log"
call xsim  Trigger_testbench_behav -key {Behavioral:sim_1:Functional:Trigger_testbench} -tclbatch Trigger_testbench.tcl -view C:/Users/mrigatti/Desktop/CRV/2.Firmware/FEB/DDR_Interface_testbench_behav.wcfg -view C:/Users/mrigatti/Desktop/CRV/2.Firmware/FEB/Trigger_testbench_behav2.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
