# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/mrigatti/Desktop/CRV/2.Firmware/FEB/FEB.srcs/sources_1/ip/DPRAM_1Kx16_1/DPRAM_1Kx16.xci
# IP: The module: 'DPRAM_1Kx16' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/mrigatti/Desktop/CRV/2.Firmware/FEB/FEB.gen/sources_1/ip/DPRAM_1Kx16/DPRAM_1Kx16_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DPRAM_1Kx16'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/mrigatti/Desktop/CRV/2.Firmware/FEB/FEB.srcs/sources_1/ip/DPRAM_1Kx16_1/DPRAM_1Kx16.xci
# IP: The module: 'DPRAM_1Kx16' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/mrigatti/Desktop/CRV/2.Firmware/FEB/FEB.gen/sources_1/ip/DPRAM_1Kx16/DPRAM_1Kx16_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DPRAM_1Kx16'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
