set_property PACKAGE_PIN M4 [get_ports {AFE0Clk_P}]
set_property PACKAGE_PIN AA6 [get_ports {AFE1Clk_P}]
set_property PACKAGE_PIN AB10 [get_ports {AFECS[0]}]
set_property PACKAGE_PIN AA10 [get_ports {AFECS[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {AFE1Clk_P}]
set_property IOSTANDARD LVDS_25 [get_ports {AFE1Clk_N}]
set_property IOSTANDARD LVDS_25 [get_ports {AFE0Clk_P}]
set_property IOSTANDARD LVDS_25 [get_ports {AFE0Clk_N}]
set_property IOSTANDARD LVCMOS25 [get_ports {AFECS[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {AFECS[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {AFE1Dat_P[7]}]
set_property IOSTANDARD LVDS_25 [get_ports {AFE1Dat_P[6]}]
set_property IOSTANDARD LVDS_25 [get_ports {AFE1Dat_P[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {AFE1Dat_P[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {AFE1Dat_P[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {AFE1Dat_P[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {AFE1Dat_P[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {AFE1Dat_P[0]}]
set_property PACKAGE_PIN AB5 [get_ports {AFE1Dat_P[7]}]
set_property PACKAGE_PIN AB4 [get_ports {AFE1Dat_N[7]}]
set_property PACKAGE_PIN AB3 [get_ports {AFE1Dat_P[6]}]
set_property PACKAGE_PIN AB2 [get_ports {AFE1Dat_N[6]}]
set_property PACKAGE_PIN AA2 [get_ports {AFE1Dat_P[5]}]
set_property PACKAGE_PIN AA1 [get_ports {AFE1Dat_N[5]}]
set_property PACKAGE_PIN W7 [get_ports {AFE1Dat_P[4]}]
set_property PACKAGE_PIN Y7 [get_ports {AFE1Dat_N[4]}]
set_property PACKAGE_PIN W3 [get_ports {AFE1Dat_P[3]}]
set_property PACKAGE_PIN Y3 [get_ports {AFE1Dat_N[3]}]
set_property PACKAGE_PIN V1 [get_ports {AFE1Dat_P[2]}]
set_property PACKAGE_PIN W1 [get_ports {AFE1Dat_N[2]}]
set_property PACKAGE_PIN U2 [get_ports {AFE1Dat_P[1]}]
set_property PACKAGE_PIN U1 [get_ports {AFE1Dat_N[1]}]
set_property PACKAGE_PIN T3 [get_ports {AFE1Dat_P[0]}]
set_property PACKAGE_PIN T2 [get_ports {AFE1Dat_N[0]}]
set_property PACKAGE_PIN L1 [get_ports {AFEDCLK_P[0]}]
set_property PACKAGE_PIN Y6 [get_ports {AFEDCLK_P[1]}]
set_property PACKAGE_PIN K1 [get_ports {AFEDCLK_N[0]}]
set_property PACKAGE_PIN Y5 [get_ports {AFEDCLK_N[1]}]
set_property PACKAGE_PIN AA8 [get_ports {AFEPDn[0]}]
set_property PACKAGE_PIN AB7 [get_ports {AFEPDn[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {AFEPDn[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {AFEPDn[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {AFEDCLK_N[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {AFEDCLK_N[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {AFEDCLK_P[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {AFEDCLK_P[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {AFE1FCLK_N}]
set_property IOSTANDARD LVDS_25 [get_ports {AFE0FCLK_N}]
set_property IOSTANDARD LVDS_25 [get_ports {AFE1FCLK_P}]
set_property IOSTANDARD LVDS_25 [get_ports {AFE0FCLK_P}]
set_property IOSTANDARD LVDS_25 [get_ports {AFE0Dat_N[7]}]
set_property IOSTANDARD LVDS_25 [get_ports {AFE0Dat_N[6]}]
set_property IOSTANDARD LVDS_25 [get_ports {AFE0Dat_N[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {AFE0Dat_N[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {AFE0Dat_N[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {AFE0Dat_N[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {AFE0Dat_N[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {AFE0Dat_N[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {AFE0Dat_P[7]}]
set_property IOSTANDARD LVDS_25 [get_ports {AFE0Dat_P[6]}]
set_property IOSTANDARD LVDS_25 [get_ports {AFE0Dat_P[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {AFE0Dat_P[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {AFE0Dat_P[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {AFE0Dat_P[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {AFE0Dat_P[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {AFE0Dat_P[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {AFE1Dat_N[7]}]
set_property IOSTANDARD LVDS_25 [get_ports {AFE1Dat_N[6]}]
set_property IOSTANDARD LVDS_25 [get_ports {AFE1Dat_N[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {AFE1Dat_N[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {AFE1Dat_N[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {AFE1Dat_N[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {AFE1Dat_N[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {AFE1Dat_N[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports AFERst]
set_property IOSTANDARD LVCMOS25 [get_ports AFESClk]
set_property IOSTANDARD LVCMOS25 [get_ports AFESDI]
set_property IOSTANDARD LVCMOS25 [get_ports AFESDO]
set_property PACKAGE_PIN U4 [get_ports {AFE1FCLK_P}]
set_property PACKAGE_PIN U3 [get_ports {AFE1FCLK_N}]
set_property PACKAGE_PIN L8 [get_ports {AFE0FCLK_P}]
set_property PACKAGE_PIN K8 [get_ports {AFE0FCLK_N}]
set_property PACKAGE_PIN AA7 [get_ports AFERst]
set_property PACKAGE_PIN AB9 [get_ports AFESDI]
set_property PACKAGE_PIN AA9 [get_ports AFESClk]
set_property PACKAGE_PIN V7 [get_ports AFESDO]
set_property PACKAGE_PIN M2 [get_ports {AFE0Dat_P[4]}]
set_property PACKAGE_PIN M1 [get_ports {AFE0Dat_N[4]}]
set_property PACKAGE_PIN N4 [get_ports {AFE0Dat_P[5]}]
set_property PACKAGE_PIN N3 [get_ports {AFE0Dat_N[5]}]
set_property PACKAGE_PIN P3 [get_ports {AFE0Dat_P[6]}]
set_property PACKAGE_PIN P2 [get_ports {AFE0Dat_N[6]}]
set_property PACKAGE_PIN L5 [get_ports {AFE0Dat_P[3]}]
set_property PACKAGE_PIN K5 [get_ports {AFE0Dat_N[3]}]
set_property PACKAGE_PIN K3 [get_ports {AFE0Dat_P[2]}]
set_property PACKAGE_PIN K2 [get_ports {AFE0Dat_N[2]}]
set_property PACKAGE_PIN H4 [get_ports {AFE0Dat_P[1]}]
set_property PACKAGE_PIN H3 [get_ports {AFE0Dat_N[1]}]
set_property PACKAGE_PIN J3 [get_ports {AFE0Dat_P[0]}]
set_property PACKAGE_PIN H2 [get_ports {AFE0Dat_N[0]}]
set_property PACKAGE_PIN P1 [get_ports {AFE0Dat_P[7]}]
set_property PACKAGE_PIN N1 [get_ports {AFE0Dat_N[7]}]


create_clock -period 5.000 -name Clk_200MHz -waveform {0.000 2.500} [get_ports Clk_200MHz]
create_clock -period 12.500 -name Clk_80MHz -waveform {0.000 6.250} [get_ports Clk_80MHz]
create_clock -period 1.786 -name Clk_560MHz -waveform {0.000 0.893} [get_ports Clk_560MHz]






